# Generated by Django 5.1.6 on 2025-05-25 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SepetUrunu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adet", models.PositiveIntegerField()),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="SiparisUrunu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adet", models.PositiveIntegerField()),
                ("birim_fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("toplam_fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kullanici_id", models.IntegerField()),
                ("ad_soyad", models.CharField(max_length=100)),
                ("telefon", models.CharField(max_length=20)),
                ("adres", models.TextField()),
                ("sehir", models.CharField(max_length=50)),
                ("ilce", models.CharField(max_length=50)),
                ("posta_kodu", models.CharField(max_length=10)),
                ("varsayilan", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Adres",
                "verbose_name_plural": "Adresler",
                "indexes": [
                    models.Index(
                        fields=["kullanici_id"], name="urunler_adr_kullani_baaa18_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("aktif", models.BooleanField(default=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                ("aciklama", models.TextField(max_length=500)),
                (
                    "ust_kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="urunler.kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategoriler",
                "ordering": ["ad"],
            },
        ),
        migrations.CreateModel(
            name="Kullanici",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
                "indexes": [
                    models.Index(
                        fields=["email", "username"],
                        name="urunler_kul_email_1ca286_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Sepet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kullanici_id", models.IntegerField()),
                (
                    "urunler",
                    models.ManyToManyField(
                        related_name="sepetler", to="urunler.sepeturunu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Siparis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kullanici_id", models.IntegerField()),
                ("siparis_numarasi", models.CharField(max_length=100, unique=True)),
                ("toplam_tutar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "odeme_durumu",
                    models.CharField(
                        choices=[
                            ("beklemede", "Beklemede"),
                            ("odendi", "Ödendi"),
                            ("iptal", "İptal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kargo_durumu",
                    models.CharField(
                        choices=[
                            ("hazirlaniyor", "Hazırlanıyor"),
                            ("kargoda", "Kargoda"),
                            ("teslim_edildi", "Teslim Edildi"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fatura_adresi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fatura_siparisler",
                        to="urunler.adres",
                    ),
                ),
                (
                    "kargo_adresi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kargo_siparisler",
                        to="urunler.adres",
                    ),
                ),
                (
                    "urunler",
                    models.ManyToManyField(
                        related_name="siparisler", to="urunler.siparisurunu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sipariş",
                "verbose_name_plural": "Siparişler",
            },
        ),
        migrations.CreateModel(
            name="Urun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=200)),
                ("aciklama", models.TextField()),
                ("fiyat", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "indirimli_fiyat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stok", models.PositiveIntegerField(default=0)),
                (
                    "resim",
                    models.ImageField(blank=True, null=True, upload_to="urunler/"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("aktif", models.BooleanField(default=True)),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                ("guncelleme_tarihi", models.DateTimeField(auto_now=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urunler",
                        to="urunler.kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
                "ordering": ["-olusturma_tarihi"],
            },
        ),
        migrations.AddField(
            model_name="siparisurunu",
            name="urun",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="siparis_urunler",
                to="urunler.urun",
            ),
        ),
        migrations.AddField(
            model_name="sepeturunu",
            name="urun",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sepet_urunler",
                to="urunler.urun",
            ),
        ),
        migrations.CreateModel(
            name="Degerlendirme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kullanici_id", models.IntegerField()),
                ("puan", models.PositiveIntegerField()),
                ("yorum", models.TextField()),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degerlendirmeler",
                        to="urunler.urun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Değerlendirme",
                "verbose_name_plural": "Değerlendirmeler",
            },
        ),
        migrations.CreateModel(
            name="UrunOzellik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anahtar", models.CharField(max_length=200)),
                ("deger", models.CharField(max_length=200)),
                (
                    "urun",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ozellikler",
                        to="urunler.urun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Özelliği",
                "verbose_name_plural": "Ürün Özellikleri",
            },
        ),
        migrations.CreateModel(
            name="Odeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tutar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "odeme_tipi",
                    models.CharField(
                        choices=[
                            ("kredi_karti", "Kredi Kartı"),
                            ("havale", "Havale"),
                            ("kapida_odeme", "Kapıda Ödeme"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("beklemede", "Beklemede"),
                            ("tamamlandi", "Tamamlandı"),
                            ("iptal", "İptal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("islem_no", models.CharField(max_length=100)),
                (
                    "siparis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odemeler",
                        to="urunler.siparis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme",
                "verbose_name_plural": "Ödemeler",
                "indexes": [
                    models.Index(
                        fields=["siparis", "islem_no", "durum"],
                        name="urunler_ode_siparis_cd1af9_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="siparis",
            index=models.Index(
                fields=[
                    "kullanici_id",
                    "siparis_numarasi",
                    "odeme_durumu",
                    "kargo_durumu",
                ],
                name="urunler_sip_kullani_7e39d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="degerlendirme",
            index=models.Index(
                fields=["urun", "kullanici_id"], name="urunler_deg_urun_id_b184e9_idx"
            ),
        ),
    ]
